### ISSUE TITLE
1 Hour + issues

### ISSUE THREAD

**Issue by ghost** [jeffkibuule/JSKTimerView#3]
So up till 3599 everything works fine and show properly. Once I switch to 3600 seconds the display is all wacky. Any idea why?

```
[timerView setTimerWithDuration:[[timerObject duration] integerValue]];
```

1 Hour (3600 seconds)
Before timer starts 
![ios simulator screen shot feb 15 2015 1 11 20 am](https://cloud.githubusercontent.com/assets/1516560/6202308/97875028-b4af-11e4-8719-7bbf7c8d312d.png)
Once timer starts
![ios simulator screen shot feb 15 2015 1 11 23 am](https://cloud.githubusercontent.com/assets/1516560/6202309/9fdac98a-b4af-11e4-9acc-0eaa70e6fd28.png)

Same issue for 12 hours (43200 seconds)
Before timer starts
![ios simulator screen shot feb 15 2015 1 13 07 am](https://cloud.githubusercontent.com/assets/1516560/6202313/d91069c6-b4af-11e4-9305-00b6b7a2d693.png)

Once started 
![ios simulator screen shot feb 15 2015 1 13 11 am](https://cloud.githubusercontent.com/assets/1516560/6202314/df4c4814-b4af-11e4-898e-97229273696a.png)

**Comment by jeffkibuule** [comment]
@pyraego Thanks for that, it's from a rookie error in `updateLabel`. I'll fix it.

**Comment by ghost** [comment]
Thank you! Let me know when you add the setter for the label color related to my pull request.

**Comment by jeffkibuule** [comment]
@pyraego Will do.
